# ==========================================
# Stage 1 - Build Angular
# ==========================================
FROM node:22 AS frontend-build

WORKDIR /app/client

COPY client/package*.json ./

RUN npm ci

COPY client/ .

RUN npm run build


# ==========================================
# Stage 2 - Build Spring Boot
# ==========================================
FROM maven:3.9-eclipse-temurin-25 AS backend-build

WORKDIR /app

COPY pom.xml .
COPY calorie-calculator/pom.xml calorie-calculator/pom.xml

RUN mvn dependency:go-offline -pl calorie-calculator -am

COPY calorie-calculator calorie-calculator

# Copy Angular build into Spring Boot static resources
COPY --from=frontend-build /app/client/dist/client/browser \
    /app/calorie-calculator/src/main/resources/static

RUN mvn clean package -DskipTests -pl calorie-calculator -am


# ==========================================
# Stage 3 - Runtime
# ==========================================
FROM eclipse-temurin:25-jre

WORKDIR /app

COPY --from=backend-build \
    /app/calorie-calculator/target/*.jar \
    app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
