FROM maven:3.9-eclipse-temurin-25 AS build

WORKDIR /app

COPY pom.xml .
COPY calorie-calculator/pom.xml calorie-calculator/pom.xml

RUN mvn dependency:go-offline -pl calorie-calculator -am

COPY calorie-calculator calorie-calculator

RUN mvn clean package -DskipTests -pl calorie-calculator -am


FROM eclipse-temurin:25-jre

WORKDIR /app

COPY --from=build /app/calorie-calculator/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
