### Database / Datasource ###
spring.datasource.url=jdbc:postgresql://localhost:5432/calories
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

### Liquibase ###
spring.liquibase.change-log=classpath:db/changelog/master.xml
spring.liquibase.enabled=true

### JPA ###
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.generate-ddl=false

### Logging ###
logging.level.org.springframework.web=DEBUG
logging.level.br.com.colatina.fmf.algafood.service=DEBUG
logging.level.liquibase=INFO

### Server ###
server.port=8080



### Swagger ###
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

### Exception ###
server.error.include-message=always

### Console ###
spring.output.ansi.enabled=always

### Debug ###
spring.jpa.show-sql=true
